### ISSUE TITLE
Typos in French "Materials" page template / translation file

### ISSUE THREAD

**Issue by DrGFreeman** [RaspberryPiFoundation/python-curriculum#108]
There are typos in the French template / translation file used to render the "Materials" page of projects.

The translation for the volunteer's resources section should read "Ressources des bénévoles" instead of "Ressources des bé né voles" (no spaces after "é" characters). See example at : https://codeclubprojects.org/fr-FR/python/rpg/materials.html

Also, the same typo is found in the word "éventail" on the French Resources page:
https://codeclubprojects.org/fr-FR/resources/

**Comment by rik-cross** [comment]
Thanks @DrGFreeman -- I think it must have been a unicode copy-paste issue. 

I've updated these now -- changes will be live later today.
