### ISSUE TITLE
non-Trinket Compatibiity

### ISSUE THREAD

**Issue by tracygardner** [RaspberryPiFoundation/python-curriculum#86]
Some projects may need modifications to run outside Trinket. (And those modifications may not work in Trinket due to limitations in its implementation.)

Would make sense to test all the projects and make sure they run on a Pi with IDLE. 

Some Code Clubs are trying to complete the projects on iOS which has also not been tested. 

Issues reported for:

Codecraft
ISS 
- "This code is giving an error. This is correct:
url=""http://api.open-notify.org/astros.json""
response=urllib.request.urlopen(url).read().decode(""utf-8"")
result=json.loads(response)"
(The code in the project runs in Trinket, but the modification is needed elsewhere.)
- Yes, there are 2 issues. First, screen.bgpic(imagefile) does not support .jpg file. Second, the register_shape(imagefile) only supports .gif file
- the graphics you provide in the "Project Materials" section are GIF files instead of JPG and PNG as stated in the script.
- Turtle projects "I dont think this works in trinket.io using Python3 - only Python?" Turtle doesn't work in Python 3 trinkets

**Comment by emik101** [comment]
line 175 in codecraft.py reads rendererT.color('')
A color needs to be assigned for this to run offline in python. That gets rid of the NoneType is not iterable error. Another error is that the player.gif image does not seem to show on the canvas. It is likely that converting the file from png to gif format has not transferred the transparency, or caused some other error. In any situation using the default arrow turtle and assigning the color "Black" in line 175 allows it to work perfectly on my raspberry pi.

**Comment by caitlynraspberrypi** [comment]
Fixed line 175 and notified for language changes.

**Comment by ninaszymor** [comment]
Spanish and Dutch updated.

**Comment by martinohanlon** [comment]
I have updated the codecraft project on the project site to be compatible both online and offline. The changes are here https://github.com/raspberrypilearning/codecraft/pull/42.

I could retrofit the changes into here, just not sure if I should be? @tracygardner any advice?

**Comment by martinohanlon** [comment]
I have update the where-is-the-space-station projects to be compatible online and offline. The changes are here https://github.com/raspberrypilearning/where-is-the-space-station/pull/20 .
