### ISSUE TITLE
Guidance for French translation

### ISSUE THREAD

**Issue by DrGFreeman** [RaspberryPiFoundation/python-curriculum#93]
Hello, I would like to contribute translating Code Club Python resources to french (currently not available on codeclubworld.org).

I followed the procedure at https://github.com/RaspberryPiFoundation/curriculum_documentation/blob/master/contributing.md and cloned this repository and noticed multiple discrepancies between the content of the repository and what is available on codeclubworld.org.

For instance, the fr-FR folder of the repository seems to have some Python content that is 1) not in-line with the english content and 2) not available on codeclubworld.org under "Français".

Also, as another example, the ASCII Art lesson folder of the en-GB folder of the repository contains images of idle that do not match the content at codeclubprojects.org/en-GB/python/about-me/.

Before I start investing time in doing translation, I would like some guidance on how to proceed to ensure I work on the right version of the code. 

Thanks and regards.

**Comment by DrGFreeman** [comment]
OK, I realized the **new-layout** branch is the one I should be working on. This explains the discrepancies I notice between the content on the Code Club website and the repository.

I have started translating from the **master** branch but I will be able to move the translation to the **new-layout** branch easily.

Got about 80% of the _About Me_ project translated including images ;)

This issue can be closed. Maybe just a confirmation I'm on the right path would be appreciated.

Thx!

**Comment by rik-cross** [comment]
Hi @DrGFreeman 

You're right that different branches are used for the different sites:

+ The `master`branch is used for the projects.codeclubworld.org site
+ The `new-layout` branch is used for the codeclubprojects.org site

The projects in the different branches have slightly different frontmatter at the top of the project, but other than that the markdown is the same.

That's great that you got most of the "About Me" project translated... I'll close this issue but feel free to get in touch if you need any additional support.

Thanks,
Rik.

**Comment by DrGFreeman** [comment]
Thank you @rik-cross!

**Comment by Matella15** [comment]
Hi @DrGFreeman, thanks so much for your work on translating, I'm glad you figured out how to complete these translations in the new branch. 

If it's okay, I need to ask you to pause before translating any more projects into French. What you've done is absolutely perfect, but we already have someone already doing some work on the French projects and I want to make sure we're not duplicating any work before we proceed.

I'll let you know next steps asap if that's okay?

**Comment by DrGFreeman** [comment]
Hi @Matella15,

That's fine, I will pause for now. I am currently on vacation and was planning to translate 2-3 other projects in the next couple of weeks. So if you know which projects are not in the process of translation let me know and I'll be glad to work on those ones.

Best regards,
Julien

**Comment by Matella15** [comment]
Thanks @DrGFreeman, that's great news. We'd be looking for you to work on a few Python projects - we're just finalising details with a couple of other volunteers but we should be able to tell you exactly which projects we'd need your help with tomorrow. 
Would I be able to get an email address for you in the meantime? No need to post publicly- you can email me directly on katherine@raspberrypi.org if you prefer.
