### ISSUE TITLE
French "About Me - Materials" page - translation of section titles and links text

### ISSUE THREAD

**Issue by DrGFreeman** [RaspberryPiFoundation/python-curriculum#98]
The Project Materials page of the French translated project **About Me** at https://codeclubprojects.org/fr-FR/python/about-me/materials.html needs translation of section titles and of the text corresponding to the links at the right of each document.

The English equivalent has the section titles **Project Resources** and **Volunteer Resources** as well as **Get** text for the different links.  The French version shows **title** and **text**. It looks like these titles are not part of the project itself but of some other template used to render the site. I can help with translation of these but I would need to know where to change it.

Thx!

**Comment by rik-cross** [comment]
Hi @DrGFreeman 

Thanks for spotting this. There are translations for these words (in a separate translations file as you mention), but they aren't being used when generating the page.

**Comment by damienh** [comment]
All fixed :)
