### ISSUE TITLE
French "About Me" Volunteer Notes page missing background image

### ISSUE THREAD

**Issue by DrGFreeman** [RaspberryPiFoundation/python-curriculum#99]
The French version of the **About Me** project volunteer notes page (https://codeclubprojects.org/fr-FR/python/about-me/About%20Me%20-%20notes.html) is missing the background image (green wavy background). The `large_banner.png` is present in the root of the fr-FR folder (**new-layout** branch) and shows up on the project and materials page so the issue seems related to the template used to render the Volunteer Notes page.

Inspection of the html file show the image url as `/fr/python/large_banner.png`:

`<header class="page" style="background: url(/fr/python/large_banner.png); background-repeat: repeat !important;">`
  
whereas the project page shows the url as `/fr-FR/python/large_banner.png`.

`<header class="lesson" style="background: url(/fr-FR/python/large_banner.png); background-repeat: repeat !important;">`

Thx.

**Comment by rik-cross** [comment]
Hi @DrGFreeman 

I've had a look at this, and it's related to the language code specified in the Project Notes `.md` file.

I've changed the file to provide the correct language code (see https://github.com/RaspberryPiFoundation/python-curriculum/commit/024459a7b02a189010052fcb3c0d6f69e1991907).
